name: Secret Password Workflow

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV
          export PASSWORD=${{ secrets.PASSWORD }}

      - name: Example Step using Secret Password
        run: |
          echo "Using secret password: $PASSWORD"
          # Add your commands here that require the secret password
